[tools]
fzf = "latest"
"aqua:ogham/exa" = "latest"
bat = "latest"
glab = "latest"
btop = "latest"
lazydocker = "latest"
lazygit = "latest"
marp-cli = "latest"
neovim = "latest"
opencode = "latest"
uv = "latest"
vault = "1.18.4"
zoxide = "latest"
node = "latest"
herdr = "latest"
